# Branch Protection Configuration
# This file documents the branch protection rules that should be applied to the main branch

# Branch Protection Rules for 'main' branch
branch_protection:
  # Require pull request reviews before merging
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    require_last_push_approval: true
    
  # Require status checks to pass before merging
  required_status_checks:
    strict: true
    contexts:
      - "Backend Lint (black + flake8)"
      - "Backend Typecheck (mypy)"
      - "Backend Test (pytest)"
      - "Frontend Test (TypeScript + Jest)"
      - "API Test (FastAPI endpoints)"
      - "Security Scan (Bandit + Safety)"
      - "Quality Gate (60% coverage)"
      
  # Require branches to be up to date before merging
  enforce_admins: false
  
  # Restrict pushes to the main branch
  restrictions:
    users: []
    teams: []
    
  # Allow force pushes (disabled for safety)
  allow_force_pushes: false
  
  # Allow deletions (disabled for safety)
  allow_deletions: false
  
  # Require linear history
  required_linear_history: true
  
  # Allow squash merging
  allow_squash_merge: true
  
  # Allow merge commits (disabled for cleaner history)
  allow_merge_commit: false
  
  # Allow rebase merging
  allow_rebase_merge: true
  
  # Require conversation resolution before merging
  required_conversation_resolution: true

# Additional protection rules
additional_rules:
  # Require signed commits (if available)
  require_signed_commits: false
  
  # Require commit message format
  commit_message_format: "^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,50}"
  
  # Minimum number of reviewers
  min_reviewers: 1
  
  # Maximum number of reviewers
  max_reviewers: 3
